# SQLite version 3.x
#   gem install sqlite3
#
#   Ensure the SQLite 3 gem is defined in your Gemfile
#   gem 'sqlite3'
default: &default
  adapter: mysql2
  encoding: utf8
  pool: 5
  username: abc
  password: meme
  socket: /var/run/mysqld/mysqld.sock

development: 
  adapter: mysql2
  encoding: utf8
  database: sigma_development
  pool: 5
  username: abc
  password: meme
  socket: /var/run/mysqld/mysqld.sock

